const definitions={
event:[['title','text',1],['summary','area',1],['media','media',1],['starts_at','datetime',1],['ends_at','datetime',1],['city','city',1],['space_id','space',1],['venue_name','text',1],['address','text',1],['organization_id','organization',1],['capacity','number',2],['paid','switch',2],['price_minor','number',2],['approval_required','switch',2],['join_methods','methods',2],['description','area',2]],
campaign:[['title','text',1],['kicker','text',1],['media','media',1],['introduction','area',1],['organization_id','organization',1],['event_ids','events',2],['resource_links','area',2]],
profile:[['avatar_url','image',1],['display_name','text',1],['wechat','text',3],['city','city',1],['bio','text',1],['interests','interests',2],['introduction','area',2],['work_links','links',4],['social_links','links',4],['frequent_spaces','spaces',4]],
entity:[['cover_url','image',1],['name','text',1],['city','city',1],['opening_hours','text',1],['address','text',1],['introduction','area',1],['public_contact','text',1],['allow_event_requests','switch',1]]
};
function fields(kind,step,t,values){return definitions[kind].filter(x=>(!step||x[2]===step)&&!(x[0]==='price_minor'&&!values.paid)&&!(['venue_name','address'].includes(x[0])&&kind==='event'&&values.space_id)).map(([key,type])=>({key,type,label:t[key]||key,value:values[key]===undefined?'':values[key]}));}
function toForm(r={}){const methods=r.access?.methods|| (r.access?[r.access]:[]);return {...r,tags:(r.tags||[]).join(', '),interests:Array.isArray(r.interests)?r.interests:[],work_links:r.work_links||r.public_links?.filter(x=>x.kind!=='social').map(x=>x.url)||[],social_links:r.social_links||r.public_links?.filter(x=>x.kind==='social').map(x=>x.url)||[],media:r.media|| (r.cover_url?[{type:'image',url:r.cover_url,label:'封面图片'}]:[]),resource_links:(r.resource_links||[]).join('\n'),paid:r.price_minor>0,price_minor:r.price_minor==null?'':String(r.price_minor/100),join_methods:methods.length?methods.map(x=>x.type):['ORGANIZER_WILL_CONTACT'],access_values:Object.fromEntries(methods.map(x=>[x.type,x.value])),access_type:r.access?.type||'ORGANIZER_WILL_CONTACT',access_value:r.access?.value||''};}
function payload(kind,f){const p={...f};for(const k of ['access_type','access_value','join_methods','access_values','paid','work_links','social_links'])delete p[k];
 if(kind==='event'){p.capacity=f.capacity===''||f.capacity==null?null:Number(f.capacity);p.price_minor=f.paid?Math.round(Number(f.price_minor||0)*100):0;p.tags=String(f.tags||'').split(/[,，]/).map(s=>s.trim()).filter(Boolean);const methods=(f.join_methods||[f.access_type||'ORGANIZER_WILL_CONTACT']).map(type=>({type,value:f.access_values?.[type]|| (type===f.access_type?f.access_value:'')||''}));p.access={...methods[0],methods};p.visibility='PUBLIC';p.approval_required=!!f.approval_required;p.waitlist_enabled=f.waitlist_enabled!==false;}
 if(kind==='profile'){p.interests=Array.isArray(f.interests)?f.interests:String(f.interests||'').split(/[,，]/).map(s=>s.trim()).filter(Boolean);p.public_links=[...(f.work_links||[]).filter(Boolean).map(url=>({kind:'work',label:'作品与项目',url})),...(f.social_links||[]).filter(Boolean).map(url=>({kind:'social',label:'社交媒体',url}))];}
 if(kind==='campaign')p.resource_links=String(f.resource_links||'').split('\n').map(s=>s.trim()).filter(Boolean);
 if(kind==='event'||kind==='campaign')p.cover_url=(f.media||[]).find(x=>x.type==='image')?.url||f.cover_url||'';
 return p;
}
module.exports={fields,toForm,payload};
