const api=require('./api'),prefs=require('./preferences'),i18n=require('./i18n'),theme=require('./theme'),dates=require('./dates'),forms=require('./forms');
const tabs=['feed','discover','messages','me'];
function go(route,id='',extra={}){const query=Object.entries({...extra,...(id?{id}:{})}).map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&');const url='/pages/'+route+'/index'+(query?'?'+query:'');return tabs.includes(route)?wx.switchTab({url}):wx.navigateTo({url});}
const formKinds={publish:'event','campaign-create':'campaign','campaign-edit':'campaign','edit-profile':'profile',onboarding:'profile','edit-entity':'entity'};
function normalize(item,t,locale){const e=item.event||item,phase=require('./mine-phase')(item);const notificationMatch=String(item.description||'').match(/^(.*?)(「[^」]+」)(.*)$/);return {...item,notificationTime:item.display_time||dates.format(item.created_at,locale),notificationParts:notificationMatch?notificationMatch.slice(1):null,notificationIcon:item.category==='ADMIN'?'review':item.category==='SOCIAL'?'new':'ticket',phase,phaseLabel:phase==='ENDED'?(locale==='en'?'Ended':'已结束'):phase==='UPCOMING'?(locale==='en'?'Upcoming':'即将开始'):t[phase]||phase,cityLabel:locale==='en'?item.city:({shanghai:'上海',beijing:'北京',guangzhou:'广州',shenzhen:'深圳',hangzhou:'杭州',chengdu:'成都'}[item.city]||item.city),activeRegistration:item.registration&&!['CANCELLED','REJECTED','EXPIRED','REFUNDED'].includes(item.registration.status),title:item.title||item.event?.title||item.display_name||item.name||t[item.key]||'',statusLabel:t[item.status]||item.status||'',dateLabel:dates.format(e.starts_at,locale),dateOnly:dates.format(e.starts_at,locale).slice(0,10),timeOnly:dates.format(e.starts_at,locale).slice(11,16),endTime:dates.format(e.ends_at,locale).slice(11,16),participantNames:(e.participants||[]).slice().sort((a,b)=>Number(b.owner===e.owner)-Number(a.owner===e.owner)).slice(0,2).map(x=>x.display_name).join(locale==='en'?' and ':'和 '),detailParticipants:(e.participants||[]).slice().sort((a,b)=>Number(b.owner===e.owner)-Number(a.owner===e.owner)).slice(0,3),participantOverflow:Math.max(0,(e.registered||0)-(e.participants||[]).length),bookingLabel:e.status==='CANCELLED'?t.CANCELLED:e.ends_at&&e.ends_at<new Date().toISOString()?(locale==='en'?'Past':'已结束'):e.remaining===0?t.full:(locale==='en'?'Upcoming':'报名中'),feeLabel:e.price_minor===0?t.free:e.price_minor!=null?'¥'+(e.price_minor/100).toFixed(2):'',route:item.route||(['event','campaign'].includes(item.type)?item.type:item.type==='registration'?'event-access':item.type==='review'?(item.subject_type==='campaign'?'campaign-approval-detail':'approval-detail'):item.type==='entity'?(item.kind==='SPACE'?'space':'org'):'member'),event:item.event?normalize(item.event,t,locale):null};}
module.exports=function createPage(route){return {
 data:{route,theme:theme.style(),t:{},sheetCopy:{},loading:true,busy:false,error:'',items:[],people:[],campaigns:[],spaces:[],organizations:[],form:{},fields:[],step:1,formKind:formKinds[route]||'',sheet:'',sheetForm:{},filters:{},offset:0,calendarMode:'week',days:[],record:null,cityName:'',selectedDate:'',hasMore:false,nextCursor:null,consent:false,shareContact:false},
 onLoad(options){this.options=options||{};this.setData({optionsId:this.options.id||'',reviewIndex:api.isMock()&&this.options.reviewIndex!==undefined?Number(this.options.reviewIndex):-1});this.filters={};this.calendarSelectionInitialized=false;this.commandKeys={};this.refreshLanguage();const kind=formKinds[route];if(kind){const cached=wx.getStorageSync(this.draftKey());this.setData({form:cached||forms.toForm({city:prefs.get().city,price_minor:0,capacity:'',approval_required:false,waitlist_enabled:true,event_ids:[],interests:[]}),step:api.isMock()&&Number(this.options.step)||wx.getStorageSync(this.draftKey()+'.step')||1});this.updateFields();}},
 onShow(){this.setData({access:null,reviewCount:0,needsLogin:false,canRegister:false,contact:null});this.refreshLanguage();this.load();},
 onUnload(){clearTimeout(this.saveTimer);},
 onPageScroll(e){this.reviewScrollTop=e.scrollTop;},
 reviewScroll(e){if(!api.isMock()||this.data.reviewIndex<0)return;wx.pageScrollTo({scrollTop:Math.max(0,(this.reviewScrollTop||0)+Number(e.currentTarget.dataset.delta)*500),duration:0});},
 onPullDownRefresh(){this.load().finally(()=>wx.stopPullDownRefresh());},
 onReachBottom(){if(this.data.hasMore&&!this.data.loading)this.load(true);},
 onShareAppMessage(){return {title:this.data.record?.title||'706',path:'/pages/'+route+'/index'+(this.options.id?'?id='+encodeURIComponent(this.options.id):'')};},
 refreshPeople(){return this.run(async()=>{this.peopleOffset=(this.peopleOffset||0)+2;const r=await this.read('people',api.isMock()?{prototype:true,offset:this.peopleOffset}:{city:this.data.city,exclude:this.data.people.map(x=>x.owner)});this.setData({people:r.items.slice(0,4)});});},
 refreshLanguage(){const p=prefs.get(),t=i18n.dictionary(p.locale);this.setData({t,sheetCopy:require('./sheet-copy')(p.locale),locale:p.locale,city:p.city,title:t[route]||'706',demo:api.isMock(),mode:api.mode(),demoName:api.isMock()?api.mock.personas.find(x=>x.id===api.session()?.id)?.label||'游客':'',currentUser:api.session()?.id||'',cityName:this.config?.cities.find(c=>c.id===p.city)?.[p.locale==='en'?'en':'zh']||t.city});if(!tabs.includes(route))wx.setNavigationBarTitle({title:t[route]||'706',demo:api.isMock(),mode:api.mode(),demoName:api.isMock()?api.mock.personas.find(x=>x.id===api.session()?.id)?.label||'游客':'',currentUser:api.session()?.id||'',cityName:this.config?.cities.find(c=>c.id===p.city)?.[p.locale==='en'?'en':'zh']||t.city});tabs.forEach((r,index)=>wx.setTabBarItem({index,text:t[r]}));},
 draftKey(){return '706.draft.'+api.mode()+'.'+(api.isMock()?api.mock.state().version+'.':'')+route+'.'+(this.options.id||'new')+'.'+(api.session()?.id||'anonymous');},
 read(op,params={}){return api.call('read',{op,params});},
 async allMine(kind){let items=[],cursor;do{const r=await this.read('mine',{kind,cursor});items.push(...r.items);cursor=r.has_more?r.next_cursor:null;}while(cursor);return items;},
 async write(op,params={}){const fingerprint=op+JSON.stringify(params);const key=this.commandKeys[fingerprint]||(this.commandKeys[fingerprint]='cmd-'+Date.now()+'-'+Math.random().toString(36).slice(2));const r=await api.call('write',{op,params,key});delete this.commandKeys[fingerprint];return r;},
 async load(append=false){
  append=append===true;
  if(this.data.loading&&this.loadingPromise)return this.loadingPromise;
  this.setData({loading:true,error:'',contact:null,access:null});
  this.loadingPromise=this.loadData(append).catch(e=>{const needsLogin=/LOGIN_REQUIRED|VERIFIED_LOGIN/.test(e.message||e.code||'');this.setData({error:i18n.message(e,this.data.t),needsLogin,...(needsLogin?{record:null,items:[],form:{},fields:[],me:null,managed:[],reviewCount:0,contact:null,access:null}: {})});}).finally(()=>{this.setData({loading:false});this.loadingPromise=null;if(!this.data.error)this.applyPreview();});return this.loadingPromise;
 },
 applyPreview(){if(!api.isMock()||this.previewApplied)return;this.previewApplied=true;if(this.options.submitted)this.setData({submitted:true});if(this.options.sheet)this.sheet({currentTarget:{dataset:{kind:this.options.sheet}}});},
 async loadData(append){
  if(['login','feedback'].includes(route))return;if(route!=='review-lab')await prefs.sync();this.refreshLanguage();const t=this.data.t,p=prefs.get(),id=this.options.id;let result;
  if(route==='review-lab'){this.loadLab();return;}
  if(!this.config){this.config=await this.read('config');this.setData({cities:this.config.cities,cityName:this.config.cities.find(c=>c.id===p.city)?.[p.locale==='en'?'en':'zh']});}
  if(route==='calendar'&&this.options.scene&&!this.shareLoaded){const share=await this.read('calendarShare',{id:decodeURIComponent(this.options.scene)});this.filters=share.params;this.shareLoaded=true;this.calendarSelectionInitialized=true;const start=share.params.from;this.sharedRange={from:start,to:share.params.to};const month=Date.parse(share.params.to)-Date.parse(start)>7*86400000;const base=dates.range(month?'month':'week');const a=dates.localDate(new Date(start)).split('-').map(Number),b=dates.localDate(new Date(base.from)).split('-').map(Number);const offset=month?(a[0]-b[0])*12+a[1]-b[1]:Math.floor((Date.parse(start)-Date.parse(base.from))/604800000);this.setData({calendarMode:month?'month':'week',offset,selectedDate:Date.parse(share.params.to)-Date.parse(start)===86400000?dates.localDate(new Date(start)):'',city:share.params.city,cityName:this.config.cities.find(c=>c.id===share.params.city)?.[p.locale==='en'?'en':'zh']});}
  const params={...this.filters,city:this.filters.city||p.city,cursor:append?this.data.nextCursor:null};this.setData({city:params.city,cityName:this.config.cities.find(c=>c.id===params.city)?.[p.locale==='en'?'en':'zh']});
  if(route==='feed'){result=await this.read('feed',{...params,prototype:api.isMock()});const people=await this.read('people',api.isMock()?{prototype:true,offset:this.peopleOffset||0}:{city:p.city});this.setData({people:people.items.slice(0,4)});}
  else if(route==='discover'||route==='calendar'){
   let range=dates.range(this.data.calendarMode,this.data.offset,this.data.selectedDate);if(this.sharedRange){const days=[];for(let n=Date.parse(this.sharedRange.from);n<Date.parse(this.sharedRange.to);n+=86400000){const date=dates.localDate(new Date(n));days.push({date,label:Number(date.slice(-2))});}range={...this.sharedRange,days,label:days[0].date+' — '+days[days.length-1].date};}this.setData({rangeLabel:range.label});
   const all=await this.read('calendar',{...params,from:range.from,to:range.to});
   if(route==='calendar'&&!this.calendarSelectionInitialized){this.calendarSelectionInitialized=true;if(!this.data.selectedDate&&this.data.calendarMode!=='month'){const first=all.items[0]?dates.localDate(new Date(all.items[0].starts_at)):dates.localDate();this.setData({selectedDate:range.days.some(d=>d.date===first)?first:range.days[0].date});}}
   let days=range.days.map(d=>({...d,count:all.items.filter(e=>Date.parse(e.starts_at)<Date.parse(d.date+'T00:00:00+08:00')+86400000&&Date.parse(e.ends_at)>Date.parse(d.date+'T00:00:00+08:00')).length}));
   if(this.data.calendarMode==='month'){const weekday=(new Date(new Date(range.from).getTime()+8*3600000).getUTCDay()+6)%7;days=[...Array.from({length:weekday},(_,i)=>({date:'blank-'+i,label:'',disabled:true})),...days];}
   days=days.map(d=>({...d,selected:d.date===this.data.selectedDate,events:all.items.filter(e=>Date.parse(e.starts_at)<Date.parse(d.date+'T00:00:00+08:00')+86400000&&Date.parse(e.ends_at)>Date.parse(d.date+'T00:00:00+08:00')).map(e=>({id:e.id,title:e.title})),weekday:d.disabled?'':['日','一','二','三','四','五','六'][new Date(d.date+'T12:00:00+08:00').getUTCDay()]}));this.setData({days,monthLabel:range.label.slice(0,7),weekdays:this.data.locale==='en'?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:['一','二','三','四','五','六','日'],rangeSpaceCount:new Set(all.items.map(x=>x.space_id||x.venue_display)).size});const items=this.data.selectedDate?all.items.filter(e=>Date.parse(e.starts_at)<Date.parse(this.data.selectedDate+'T00:00:00+08:00')+86400000&&Date.parse(e.ends_at)>Date.parse(this.data.selectedDate+'T00:00:00+08:00')):all.items;
   const dayKeys=this.data.selectedDate?[this.data.selectedDate]:days.filter(d=>!d.disabled).map(d=>d.date);const timeline=require('./calendar-layout').timeline(all.items.map(e=>normalize(e,t,p.locale)),dayKeys),firstEvent=timeline.days.flatMap(d=>d.events).sort((a,b)=>a.top-b.top)[0];this.setData({timeline,timelineScrollLeft:0,timelineScrollTop:Math.max(0,(firstEvent?.top||0)-120)*(wx.getWindowInfo?wx.getWindowInfo().windowWidth/750:0.5)});result={items};if(route==='discover'){const c=await this.read('campaigns',params);this.setData({campaigns:c.items});}
   const s=await this.read('entities',{kind:'SPACE',city:params.city});this.setData({spaces:api.isMock()?s.items.filter(x=>['demo-space','demo-m50','demo-riverside'].includes(x.id)):s.items});
  }
  else if(route==='event'){const r=await this.read('event',{id});this.setData({record:normalize(r,t,p.locale),comments:r.comments,detailThreads:(r.comments||[]).filter(x=>!x.reply_to&&x.source_surface!=='sheet').map(x=>({...x,replies:(r.comments||[]).filter(y=>y.reply_to===x.id)})),commentThreads:(r.comments||[]).filter(x=>!x.reply_to&&x.source_surface!=='detail').map(x=>({...x,replies:(r.comments||[]).filter(y=>y.reply_to===x.id)})),items:[],canRegister:r.can_register});return;}
  else if(route==='campaign'){const r=await this.read('campaign',{id});this.setData({record:{...r,citySummary:(r.cities||[]).join(' · ')}});result={items:r.items};}
  else if(['member','space','org','entity-events','entity-members'].includes(route)){
   const r=await this.read(route==='member'?'member':'entity',{id});this.setData({record:normalize(r,t,p.locale),memberLinks:route==='member'?['work','social'].map((kind,i)=>(r.public_links||[]).find(x=>x.kind===kind||(!x.kind&&x.label===(i?'社交媒体':'作品与项目')))).filter(Boolean):[]});result={items:route==='entity-members'?r.members.map(x=>({...x,id:x.owner,route:'member'})):r.items};
  }
  else if(route==='spaces')result=await this.read('entities',{...params,kind:'SPACE',directory:true});
  else if(route==='messages')result=await this.read('notifications',{category:this.data.category||'',cursor:params.cursor});
  else if(route==='me'){
   const [r,e,events,registrations,campaigns]=await Promise.all([this.read('me'),this.read('managed'),this.allMine('event'),this.allMine('registration'),this.allMine('campaign')]);const counts=require('./personal-summary')(events,registrations,campaigns);const en=p.locale==='en';
   const menuGroups=[{id:'events',rows:[{icon:'publish',label:en?'Publish event':'发布活动',route:'publish'},{icon:'draft',label:en?'Event drafts':'活动草稿',route:'drafts',value:String(counts.drafts)},{icon:'ticket',label:en?'My registrations':'我报名的活动',route:'registrations',value:counts.registrations+(en?' upcoming':' 场')},{icon:'flag',label:en?'My events':'我发布的活动',route:'my-events',value:counts.events+(en?' active':' 场')}]},{id:'campaigns',rows:[{icon:'series',label:en?'Create series':'发起专题',route:'campaign-create'},{icon:'review',label:en?'My series':'我发起的专题',route:counts.campaignId?'campaign-review-progress':'my-campaigns',id:counts.campaignId,value:counts.campaigns+(en?' in review':' 个审核中')}]},{id:'managed',rows:e.items.sort((a,b)=>(a.kind==='ORGANIZATION'?0:1)-(b.kind==='ORGANIZATION'?0:1)).map(x=>({icon:x.kind==='SPACE'?'home':'org',label:en?(x.kind==='SPACE'?'My managed space':'My managed organization'):(x.kind==='SPACE'?'我管理的空间':'我管理的组织'),value:x.name,route:x.kind==='SPACE'?'space':'org',id:x.id}))},{id:'more',rows:[{icon:'more',label:en?'More':'更多',route:'more'}]}];
   this.setData({record:r.profile,me:r,managed:e.items,counts,menuGroups});if(r.roles.length){const tasks=await this.read('reviews');this.setData({reviewCount:tasks.total});}return;
  }
  else if(route==='more'||route==='privacy'){const r=await this.read('me');this.setData({me:r,record:r.profile});return;}
  else if(['relations','following'].includes(route)){this.setData({relationMode:this.data.relationMode||this.options.mode||'following'});const counts=this.options.id?await this.read('member',{id:this.options.id}):await this.read('me');this.setData({followingCount:counts.following_count??counts.following,followersCount:counts.followers_count??counts.followers});result=await this.read('relations',{id:this.options.id,mode:this.data.relationMode,cursor:params.cursor});}
  else if(['registrations','my-events','drafts','my-campaigns'].includes(route))result=await this.read('mine',{kind:route==='registrations'?'registration':route==='my-campaigns'?'campaign':'event',status:route==='drafts'?'DRAFT':undefined,phase:this.data.minePhase||'',cursor:params.cursor});
  else if(route==='approvals'){result=await this.read('reviews',params);if(api.isMock()&&this.options.done)result={items:result.items.filter(x=>x.subject_type==='campaign')};}
  else if(['approval-detail','campaign-approval-detail'].includes(route)){const r=await this.read('review',{id});this.setData({record:r,subject:normalize(r.subject,t,p.locale),reviewSteps:(r.reviews||[]).filter(x=>x.status!=='SUPERSEDED')});return;}
  else if(['approval-progress','campaign-review-progress'].includes(route)){const r=await this.read('progress',{id});this.setData({record:normalize(r.subject,t,p.locale)});result={items:r.items.filter(x=>x.status!=='SUPERSEDED')};}
  else if(route==='event-access'){const r=await this.read('registration',{id});const access=r.status==='CONFIRMED'?await this.write('access',{id}):null,types=(access?.methods||[access]).filter(Boolean).map(x=>x.type);this.setData({record:normalize(r,t,p.locale),paymentDeadline:dates.format(r.payment_expires_at,p.locale),accessHasGroup:types.includes('GROUP_QR'),accessHasContact:types.includes('ORGANIZER_WECHAT'),accessWillContact:types.includes('ORGANIZER_WILL_CONTACT')});return;}
  else if(route==='attendees')result=await this.read('attendees',{id});
  else if(route==='admins')result=await this.read('admins',{id});
  else if(route==='invitations')result=await this.read('invitations');
  else if(formKinds[route]){
   if(!api.session()){this.setData({needsLogin:true});throw Error('LOGIN_REQUIRED');}
   const kind=formKinds[route];let r=null;
   if(!this.formLoaded){if(kind==='profile'){r=(await this.read('me')).profile;const contact=await this.read('selfContact');r={...r,wechat:contact.wechat};}else if(kind==='entity')r=await this.read('entity',{id});else if(id)r=await this.read('draft',{id,kind});
    const cached=wx.getStorageSync(this.draftKey());this.setData({form:cached|| (r?forms.toForm(r):this.data.form),record:r});this.formLoaded=true;}
   const es=await this.read('managed');const spaces=await this.read('entities',{kind:'SPACE'});
   this.setData({organizations:es.items.filter(e=>e.kind==='ORGANIZATION'),spaces:spaces.items});
   if(kind==='campaign'){const ev=await this.read('events',{});const mine=await this.read('mine',{kind:'event'});const options=[...ev.items,...mine.items.filter(e=>e.status==='IN_REVIEW')];for(const selected of this.data.form.event_ids||[])if(!options.some(e=>e.id===selected))options.push(await this.read('event',{id:selected}));this.setData({eventOptions:[...new Map(options.map(e=>[e.id,normalize(e,t,p.locale)])).values()]});}
   this.updateFields();await this.refreshMedia();return;
  }
  else if(route==='activity-preview'){const r=await this.read('draft',{id});this.setData({record:normalize(r,t,p.locale)});await this.refreshMedia();return;}
  else if(['more','privacy','feedback','login'].includes(route))return;
  if(result){const items=(result.items||[]).map(x=>normalize(x,t,p.locale));this.setData({items:append?[...this.data.items,...items.filter(x=>!this.data.items.some(i=>i.id===x.id))]:items,nextCursor:result.next_cursor||null,hasMore:!!result.has_more,total:result.total||items.length});}
 },
 navigate(e){if(this.data.sheet)this.closeSheet();const d=e.currentTarget.dataset;if(d.route==='space'&&!d.id)return;if(d.route==='review-lab'){wx.reLaunch({url:'/pages/review-lab/index'});return;}go(d.route,d.id||'',d.extra||{});},
 openItem(e){if(['attendees','admins','invitations','approval-progress','campaign-review-progress'].includes(route))return;const item=this.data.items[Number(e.currentTarget.dataset.index)];if(route==='messages'){this.run(async()=>{await this.write('read',{id:item.id});if(item.target?.route)go(item.target.route,item.target.id);});}else go(item.route,item.route==='member'?(item.owner||item.id):item.id);},
 openEvent(e){go('event',e.currentTarget.dataset.id);},
 mineFilter(e){this.setData({minePhase:e.currentTarget.dataset.phase});this.load();},
 bannerChange(e){this.setData({bannerIndex:e.detail.current});},
 bannerMove(e){const total=this.data.campaigns.length;this.setData({bannerIndex:((this.data.bannerIndex||0)+Number(e.currentTarget.dataset.delta)+total)%total});},
 cardRecommend(e){const d=e.currentTarget.dataset;this.run(async()=>{await this.write('recommend',{id:d.id,enabled:d.enabled});await this.load();});},
 async run(fn){if(this.data.busy)return;this.setData({busy:true,error:''});try{return await fn();}catch(e){this.setData({error:i18n.message(e,this.data.t),needsLogin:/LOGIN_REQUIRED|VERIFIED_LOGIN/.test(e.message||'')});}finally{this.setData({busy:false});}},
 login(){go('login');},
 chooseCity(){this.sheet({currentTarget:{dataset:{kind:'city'}}});},
 selectCity(e){const id=e.currentTarget.dataset.id,c=this.config.cities.find(c=>c.id===id);if(!c)return;this.sharedRange=null;delete this.filters.city;prefs.set({city:id});this.closeSheet();this.setData({city:id,cityName:c[this.data.locale==='en'?'en':'zh']});this.run(async()=>{if(api.session())await this.write('profile',{city:id});await this.load();});},
 selectLanguage(e){prefs.set({locale:e.currentTarget.dataset.locale});this.closeSheet();this.refreshLanguage();this.updateFields();this.run(async()=>{if(api.session())await this.write('profile',{locale:prefs.get().locale});await this.load();});},
 reloadPage(){this.closeSheet();this.load();},
 toggleLanguage(){prefs.set({locale:this.data.locale==='en'?'zh-CN':'en'});if(api.session())this.run(()=>this.write('profile',{locale:prefs.get().locale}));this.refreshLanguage();this.updateFields();this.load();},
 logout(){this.run(async()=>{await api.logout();wx.reLaunch({url:'/pages/feed/index'});});},
 searchInput(e){this.setData({query:e.detail.value});},
 search(){this.run(async()=>{if(!this.data.query)return this.load();const r=await this.read('search',{q:this.data.query,city:this.data.city});this.setData({items:r.items.map(x=>normalize(x,this.data.t,this.data.locale)),searching:true});});},
 timelineScrolled(e){this.timelineActualLeft=e.detail.scrollLeft;},
 moveTimeline(e){const width=wx.getWindowInfo?wx.getWindowInfo().windowWidth:375,scale=width/750,viewport=(750-56-86)*scale,max=Math.max(0,(this.data.timeline.days.length*310)*scale-viewport);this.setData({timelineScrollLeft:Math.min(max,Math.max(0,(this.timelineActualLeft||0)+Number(e.currentTarget.dataset.delta)*620*scale))});},
 filter(e){this.sharedRange=null;const {key,value}=e.currentTarget.dataset;if(key==='clearTags'){delete this.filters.tag;delete this.filters.free_only;delete this.filters.has_capacity;this.setData({filters:{...this.filters}});return this.load();}if(key==='date'&&value==='calendar'){this.setData({showWeek:!this.data.showWeek});return;}if(key==='date'){this.calendarSelectionInitialized=true;this.setData({offset:value==='next'?1:0,selectedDate:'',calendarMode:'week',showWeek:value==='calendar'});}else{if(['tag','free_only','has_capacity'].includes(key)){delete this.filters.tag;delete this.filters.free_only;delete this.filters.has_capacity;}this.filters[key]=value;this.setData({filters:{...this.filters}});}return this.load();},
 clearFilters(){this.sharedRange=null;this.calendarSelectionInitialized=true;this.filters={};this.setData({filters:{},selectedDate:'',offset:0,query:'',searching:false});return this.load();},
 period(e){this.sharedRange=null;this.calendarSelectionInitialized=true;this.setData({offset:this.data.offset+Number(e.currentTarget.dataset.delta),selectedDate:''});return this.load();},
 calendarMode(e){this.sharedRange=null;this.calendarSelectionInitialized=true;this.setData({calendarMode:e.currentTarget.dataset.mode,offset:0,selectedDate:''});return this.load();},
 clearDate(){this.sharedRange=null;this.calendarSelectionInitialized=true;this.setData({selectedDate:''});return this.load();},
 selectDay(e){const day=e.currentTarget.dataset.date;if(!day||day.startsWith('blank-'))return;this.sharedRange=null;this.calendarSelectionInitialized=true;if(this.data.calendarMode==='month'){const base=dates.range('week');const offset=Math.floor((new Date(day+'T00:00:00+08:00')-new Date(base.from))/604800000);this.setData({calendarMode:'week',offset,selectedDate:day});}else this.setData({selectedDate:this.data.selectedDate===day?'':day});return this.load();},
 relationTab(e){this.setData({relationMode:e.currentTarget.dataset.mode});this.load();},
 category(e){this.setData({category:e.currentTarget.dataset.value});this.load();},
 markRead(){this.run(async()=>{await this.write('read');await this.load();});},
 follow(e){const d=e.currentTarget.dataset;this.run(async()=>{await this.write('follow',{id:d.id,enabled:d.enabled!==false});await this.load();});},
 sheet(e){const d=e.currentTarget.dataset,kind=d.kind;this.run(async()=>{if(kind==='city'&&!this.config){this.config=await this.read('config');this.setData({cities:this.config.cities});}if(kind==='manage'&&!this.data.record?.can_manage)throw Error('FORBIDDEN');let values={};if(kind==='register'){const me=await this.read('me');values={display_name:me.profile.display_name,motivation:api.isMock()?'对城市里的公共空间很感兴趣，也想认识一起做社区的人。':''};}if(kind==='recommend')values={text:api.isMock()?'这个主题很适合第一次来 706 的朋友，一起去吧。':''};if(kind==='comment'){values={reply_to:d.reply||'',text:d.reply&&api.isMock()?'谢谢分享，我也想听听你的看法。':''};const list=this.data.comments||[];const threads=list.filter(x=>!x.reply_to&&(d.reply?x.id===d.reply:x.source_surface!=='detail')).map(x=>({...x,replies:list.filter(y=>y.reply_to===x.id)}));this.setData({commentThreads:threads,commentCount:threads.reduce((n,x)=>n+1+x.replies.length,0)});}if(kind==='return')values={note:api.isMock()?(route==='campaign-approval-detail'?'请补充各城市活动如何呼应专题主题，并替换一张缺少来源说明的图片。':'空间 18:30 前还有其他活动，请将布置时间改为 18:40 以后。'):''};if(kind==='group'){let access=await this.write('access',{id:this.options.id});const methods=[];for(const m of access?.methods||[access]){if(!m)continue;methods.push(m.type==='GROUP_QR'&&m.value?.startsWith('706-media:')?{...m,value:(await api.call('mediaPreview',{id:m.value.slice(10),registration:this.options.id})).url}:m);}this.setData({access:{...access,methods}});}if(kind==='report'&&route==='feedback')values=this.data.sheetForm;if(tabs.includes(route))wx.hideTabBar({animation:false});this.setData({sheet:kind,sheetForm:values,consent:false,shareContact:false});});},
 closeSheet(){this.setData({sheet:''});if(tabs.includes(route))wx.showTabBar({animation:false});},
 sheetInput(e){this.setData({['sheetForm.'+e.currentTarget.dataset.key]:e.detail.value});},
 consent(e){this.setData({consent:e.detail.value.length>0});},
 contactConsent(e){this.setData({shareContact:e.detail.value.length>0});},
 submitSheet(){this.run(async()=>{const kind=this.data.sheet;let result;
  if(kind==='register')result=await this.write('register',{id:this.options.id,...this.data.sheetForm,privacy_consent:this.data.consent,contact_share_consent:this.data.shareContact});
  else if(kind==='invite')result=await this.write('invite',{id:this.options.id,...this.data.sheetForm});
  else result=await this.write(kind,{id:this.options.id,...this.data.sheetForm});
  this.closeSheet();if(kind==='report'){this.setData({sheetForm:{}});wx.showToast({title:this.data.t.saved,icon:'success'});}if(kind==='register')go('event-access',result.id);else await this.load();});},
 action(e){const {op,id,approve,version}=e.currentTarget.dataset;this.run(async()=>{const p={id:id||this.options.id,version:version||this.data.record?.version,...(approve===undefined?{}:{approve})};
  if(op==='review'&&!approve){if(!this.data.sheetForm.note){this.setData({error:this.data.t.REASON_REQUIRED});return;}p.note=this.data.sheetForm.note;}
  if(['cancelEvent','cancelRegistration','revokeRole'].includes(op)){const yes=await new Promise(resolve=>wx.showModal({title:this.data.t[op]||this.data.t.confirm,success:r=>resolve(r.confirm)}));if(!yes)return;}
  if(op==='payment'){this.closeSheet();if(api.isMock()){const choice=await new Promise(resolve=>wx.showModal({title:'模拟支付',content:'仅改变本地演示状态，不会扣款。',success:r=>resolve(r.confirm)}));if(choice){await api.call('payment',p);await this.load();}return;}const r=await api.call('payment',p);await new Promise((resolve,reject)=>wx.requestPayment({...r,success:resolve,fail:reject}));await this.load();return;}
  if(op==='registrationContact'){const contact=await this.write('registrationContact',p);this.setData({contact:contact.wechat||this.data.t.noContact});return;}
  if(op==='withdrawRecommendation'){await this.write('recommend',{id:p.id,enabled:false});await this.load();return;}
  const r=await this.write(op,p);
  if(op==='clone'){go('publish',r.id);return;}if(op==='access'){if(r?.type==='GROUP_QR'&&r.value?.startsWith('706-media:')){const asset=await api.call('mediaPreview',{id:r.value.slice(10),registration:p.id});r.value=asset.url;}this.setData({access:r});return;}
  this.closeSheet();await this.load();
 });},
 updateFields(){const kind=formKinds[route];if(!kind)return;const multi=['publish','campaign-create','onboarding'].includes(route);this.setData({interestOptions:['城市观察','线下共读','独立放映','户外散步','桌游','社区营造','公共空间','一起吃饭'].map(value=>({value,selected:(this.data.form.interests||[]).includes(value)})),accessOptions:['GROUP_QR','ORGANIZER_WECHAT','ORGANIZER_WILL_CONTACT'].map(value=>({value,label:this.data.t[value],selected:(this.data.form.join_methods||[]).includes(value),content:this.data.form.access_values?.[value]||''})),fields:forms.fields(kind,multi?this.data.step:0,this.data.t,this.data.form).map(f=>({...f,display:f.type==='space'?this.data.spaces.find(x=>x.id===f.value)?.name:f.type==='organization'?this.data.organizations.find(x=>x.id===f.value)?.name:f.type==='access'?this.data.t[f.value]:f.type==='city'?this.config?.cities.find(x=>x.id===f.value)?.[this.data.locale==='en'?'en':'zh']:f.value})),spaces:this.data.spaces.map(x=>({...x,selected:(this.data.form.frequent_spaces||this.data.form.follow_spaces||[]).includes(x.id)})),venueName:this.data.spaces.find(x=>x.id===this.data.form.space_id)?.name||this.data.form.venue_name,spaceNames:[this.data.t.choose,...this.data.spaces.map(x=>x.name)],organizationNames:[this.data.t.personal,...this.data.organizations.map(x=>x.name)],eventOptions:(this.data.eventOptions||[]).map(x=>({...x,selected:(this.data.form.event_ids||[]).includes(x.id),cityLabel:this.config?.cities.find(c=>c.id===x.city)?.[this.data.locale==='en'?'en':'zh']||x.city}))});if(route==='campaign-edit'){const keys=['media','title','introduction','resource_links','event_ids'],labels=this.data.locale==='en'?['Series cover','Series name','Introduction','Resources and external links','Events in this series']:['系列封面','系列名称','总介绍','资料与外部链接','系列中的活动'];const selected=this.data.form.event_ids||[],options=this.data.eventOptions||[];this.setData({fields:keys.map((key,i)=>({...this.data.fields.find(f=>f.key===key),label:labels[i]})),visibleEventOptions:this.data.showEventPicker?options:[...selected.map(id=>options.find(x=>x.id===id)).filter(Boolean)]});}},
 listInput(e){const d=e.currentTarget.dataset,list=[...(this.data.form[d.key]||[])];list[Number(d.index)]=e.detail.value;this.setData({['form.'+d.key]:list});this.persist();},
 listAdd(e){const key=e.currentTarget.dataset.key;this.setData({['form.'+key]:[...(this.data.form[key]||[]),'']});this.persist();},
 listRemove(e){const d=e.currentTarget.dataset;this.setData({['form.'+d.key]:(this.data.form[d.key]||[]).filter((_,i)=>i!==Number(d.index))});this.persist();},
 interestsChange(e){this.setData({'form.interests':e.detail.value});this.updateFields();this.persist();},
 methodsChange(e){this.setData({'form.join_methods':e.detail.value});this.updateFields();this.persist();},
 accessInput(e){this.setData({['form.access_values.'+e.currentTarget.dataset.type]:e.detail.value});this.persist();},
 mediaRemove(e){this.setData({'form.media':(this.data.form.media||[]).filter((_,i)=>i!==Number(e.currentTarget.dataset.index))});this.persist();},
 mediaLink(){if((this.data.form.media||[]).filter(x=>x.type==='link').length>=3){this.setData({error:this.data.t.MEDIA_LIMIT});return;}this.setData({'form.media':[...(this.data.form.media||[]),{type:'link',url:'',label:''}]});this.persist();},
 mediaLinkInput(e){const list=[...(this.data.form.media||[])],i=Number(e.currentTarget.dataset.index);list[i]={...list[i],url:e.detail.value,label:e.detail.value};this.setData({'form.media':list});this.persist();},
 formatCopy(e){const key='introduction',prefix=e.currentTarget.dataset.kind==='title'?'\n## ':e.currentTarget.dataset.kind==='quote'?'\n> ':'\n\n';this.setData({['form.'+key]:(this.data.form[key]||'')+prefix});this.persist();},
 restartForm(){this.setData({submitted:false,step:1});this.updateFields();},
  input(e){const k=e.currentTarget.dataset.key;this.setData({['form.'+k]:e.detail.value});this.updateFields();this.persist();},
 switchInput(e){this.input(e);},
 select(e){const {key,type}=e.currentTarget.dataset;const v=Number(e.detail.value);let value;
  if(type==='city')value=this.config.cities[v].id;
  if(type==='space')value=v===0?'':this.data.spaces[v-1].id;
  if(type==='organization')value=v===0?'':this.data.organizations[v-1].id;
  if(type==='access')value=['GROUP_QR','ORGANIZER_WECHAT','ORGANIZER_WILL_CONTACT'][v];
  this.setData({['form.'+key]:value});this.updateFields();this.persist();
 },
 upload(e){const d=e.currentTarget.dataset,key=d.key,type=d.type||'image',isMedia=key==='media',isPrivate=key==='access_value'||key==='access_values.GROUP_QR';this.run(async()=>{const existing=this.data.form.media||[],limit=type==='video'?1:this.data.formKind==='campaign'?12:9;if(isMedia&&!d.replace&&existing.filter(x=>x.type===type).length>=limit)throw Error('MEDIA_LIMIT');const selected=await new Promise((resolve,reject)=>wx.chooseMedia({count:1,mediaType:[type],success:resolve,fail:reject}));const file=selected.tempFiles[0];if(file.size>10*1024*1024)throw Error('MEDIA_INVALID');const path=file.tempFilePath;let asset;if(api.isMock()){const saved=await new Promise((resolve,reject)=>wx.getFileSystemManager().saveFile({tempFilePath:path,success:r=>resolve(r.savedFilePath),fail:reject}));asset=api.mock.localMedia(saved);}else{const ext=(path.split('.').pop()|| (type==='video'?'mp4':'jpg')).toLowerCase();const permit=await api.call('mediaUpload',{extension:ext,private:isPrivate});const data=await new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:path,success:r=>resolve(r.data),fail:reject}));await new Promise((resolve,reject)=>wx.request({url:permit.upload_url,method:'PUT',data,header:{'content-type':type==='video'?'video/mp4':ext==='png'?'image/png':ext==='webp'?'image/webp':'image/jpeg'},success:r=>r.statusCode<300?resolve(r):reject(Error('MEDIA_INVALID')),fail:reject}));asset=await api.call('mediaFinish',{path:permit.path});}if(isMedia){const item={type,url:asset.url,label:file.tempFilePath.split('/').pop()},media=existing.slice();const cover=media.findIndex(x=>x.type==='image');if(d.replace&&cover>=0)media[cover]=item;else media.push(item);this.setData({'form.media':media});}else this.setData({['form.'+key]:isPrivate?'706-media:'+asset.id:asset.url,['mediaPreviews.'+key]:asset.preview_url||asset.url});this.updateFields();this.persist();});},
 dateInput(e){const key=e.currentTarget.dataset.key;const old=this.data.form[key]?dates.format(this.data.form[key]):dates.localDate()+' 12:00';const next=e.currentTarget.dataset.part==='date'?e.detail.value+' '+old.slice(11,16):old.slice(0,10)+' '+e.detail.value;this.setData({['form.'+key]:new Date(next.replace(' ','T')+':00+08:00').toISOString()});this.updateFields();this.persist();},
 spaceSelection(e){this.setData({'form.follow_spaces':e.detail.value,'form.frequent_spaces':e.detail.value});this.updateFields();this.persist();},
 preference(e){const kind=e.currentTarget.dataset.kind;return this.run(async()=>{const me=await this.read('me');if(kind==='share_activity'){await this.write('profile',{share_activity:!me.profile?.share_activity});wx.showToast({title:this.data.t.saved});}else if(kind==='visibility'){const visibility=me.profile?.visibility==='PUBLIC'?'MEMBERS':'PUBLIC';await this.write('profile',{visibility});wx.showToast({title:this.data.t.saved});}else{const enabled=!me.profile?.notification_preferences?.enabled;await this.write('profile',{notification_preferences:{enabled}});wx.showToast({title:this.data.t.saved});}await this.load();});},
 eventSelection(e){const next=e.detail.value,previous=this.data.form.event_ids||[];this.setData({'form.event_ids':[...previous.filter(id=>next.includes(id)),...next.filter(id=>!previous.includes(id))]});this.persist();},
 toggleEventPicker(){this.setData({showEventPicker:!this.data.showEventPicker});this.updateFields();},
 persist(){wx.setStorageSync(this.draftKey(),this.data.form);wx.setStorageSync(this.draftKey()+'.step',this.data.step);this.setData({draftSaved:true});},
 step(e){this.setData({step:Math.max(1,Math.min(3,this.data.step+Number(e.currentTarget.dataset.delta)))});this.updateFields();this.persist();},
 saveForm(e){const submit=e?.currentTarget?.dataset?.submit||(route==='campaign-edit'&&this.data.record?.status==='PUBLISHED');this.run(async()=>{
  const kind=formKinds[route], p=forms.payload(kind,this.data.form);let op=kind==='event'?'saveEvent':kind==='campaign'?'saveCampaign':kind==='profile'?'profile':'entity';
  if(kind==='profile'&&route==='onboarding'){p.complete=!!submit;p.privacy_consent=this.data.consent;}
  if(kind==='entity')p.id=this.options.id;
  if(op==='registrationContact'){const contact=await this.write('registrationContact',p);this.setData({contact:contact.wechat||this.data.t.noContact});return;}
  if(op==='withdrawRecommendation'){await this.write('recommend',{id:p.id,enabled:false});await this.load();return;}
  const r=await this.write(op,p);this.setData({form:forms.toForm({...r,...(kind==='event'?{access:p.access}:{}),...(kind==='profile'?{wechat:p.wechat,follow_spaces:p.follow_spaces}:{})}),record:r});this.persist();
  if(submit&&(kind==='event'||kind==='campaign')){await this.write(kind==='event'?'submitEvent':'submitCampaign',{id:r.id,version:r.version});wx.removeStorageSync(this.draftKey());wx.removeStorageSync(this.draftKey()+'.step');this.setData({submitted:true,submittedId:r.id});}
  else if(kind==='profile'&&submit){wx.removeStorageSync(this.draftKey());wx.removeStorageSync(this.draftKey()+'.step');this.setData({submitted:true});}
  else wx.showToast({title:this.data.t.saved,icon:'success'});
  this.updateFields();
 });},
 loginInput(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},
 sendCode(){this.run(async()=>{await api.login(this.data.loginMode||'phone',this.data.address);this.setData({codeSent:true});if(api.isMock())wx.showToast({title:'演示验证码：706000',icon:'none'});});},
 verifyCode(){this.run(async()=>{if(!String(this.data.code||'').trim())throw Error('CODE_REQUIRED');await api.login(this.data.loginMode||'phone',this.data.address,this.data.code);const me=await this.read('me');prefs.fromProfile(me.profile);if(me.profile?.onboarded)go('me');else go('onboarding');});},
 loginMode(){this.setData({loginMode:this.data.loginMode==='email'?'phone':'email',codeSent:false});},
 wechatLogin(){this.run(async()=>{if(api.isMock()){await api.call('wechatLogin');go('me');return;}const r=await new Promise((resolve,reject)=>wx.login({success:resolve,fail:reject}));const login=await api.call('wechatLogin',{code:r.code});api.setSession(login.user);const me=await this.read('me');prefs.fromProfile(me.profile);go(me.profile?.onboarded?'me':'onboarding');});},
 copy(e){wx.setClipboardData({data:e.currentTarget.dataset.value});},
 async refreshMedia(){const values=this.data.formKind?this.data.form:this.data.record||{};const out={};for(const key of ['cover_url','avatar_url','access_value']){const value=values[key];if(!value)continue;const match=value.match(/(?:706-media:|\/community\/media\/)([^/?]+)$/);if(!match)continue;try{out[key]=(await api.call('mediaPreview',{id:match[1]})).url;}catch{out[key]=key==='access_value'?'':value;}}this.setData({mediaPreviews:out});},
 previewImage(e){wx.previewImage({urls:[e.currentTarget.dataset.url]});},
 poster(){this.run(async()=>{
  const range=this.sharedRange||dates.range(this.data.calendarMode,this.data.offset);const params={...this.filters,city:this.data.city,from:range.from,to:range.to};
  if(this.data.selectedDate){params.from=new Date(this.data.selectedDate+'T00:00:00+08:00').toISOString();params.to=new Date(new Date(params.from).getTime()+86400000).toISOString();}
  const share=await api.call('calendarCode',{params}),items=share.items,renderer=require('./calendar-poster'),plan=renderer.layout(items);
  const codePath=wx.env.USER_DATA_PATH+'/706-calendar-code.png';if(!share.demo)await new Promise((resolve,reject)=>wx.getFileSystemManager().writeFile({filePath:codePath,data:share.code,encoding:'base64',success:resolve,fail:reject}));
  const covers=await Promise.all(items.map(x=>x.cover_url?new Promise(resolve=>wx.getImageInfo({src:x.cover_url,success:r=>resolve(x.cover_url.startsWith('/')?x.cover_url:r.path),fail:()=>resolve(null)})):Promise.resolve(null)));
  const period=dates.localDate(new Date(params.from))+' — '+dates.localDate(new Date(Date.parse(params.to)-86400000)),title=this.data.selectedDate?'当日活动日历':this.data.calendarMode==='month'?Number(period.slice(5,7))+' 月活动日历':'本周活动日历',space=this.data.spaces.find(x=>x.id===params.space_id)?.name||this.data.t.allSpaces,tag=params.free_only?this.data.t.free:params.has_capacity?this.data.t.capacity:params.tag?this.data.t[params.tag]:this.data.t.any;
  this.setData({posterHeight:plan.height,posterWidth:plan.width,posterPeriod:period,posterTitle:title});await new Promise(resolve=>wx.nextTick(resolve));
  const c=wx.createCanvasContext('poster',this);renderer.draw(c,plan,{city:this.data.cityName,title,period,filters:space+' · '+tag,notice:this.data.t.posterNotice,demo:share.demo,codePath,covers});
  await new Promise(resolve=>c.draw(false,resolve));const r=await new Promise((resolve,reject)=>wx.canvasToTempFilePath({canvasId:'poster',width:plan.width,height:plan.height,success:resolve,fail:reject},this));this.setData({posterPath:r.tempFilePath,sheet:'poster'});
 });},
 loadLab(){const catalog=require('./mock/catalog').map((e,index)=>({...e,index}));this.setData({personas:api.mock.personas,labState:api.isMock()?api.mock.state():null,catalog,filteredCatalog:catalog,scenarios:[{id:'normal',label:'正常数据'},{id:'loading',label:'加载中（本地延迟）'},{id:'empty',label:'空列表'},{id:'error',label:'加载失败'},{id:'permission',label:'无权限'}]});},
 labOpen(e){const entry=this.data.catalog[Number(e.currentTarget.dataset.index)];if(!api.isMock()){this.setData({error:'合成页面目录仅用于离线演示模式。'});return;}api.mock.configure({persona:entry.persona||'demo-member',scenario:'normal'});prefs.set({city:'shanghai'});const query=Object.entries({...entry.options,reviewIndex:e.currentTarget.dataset.index,...(entry.id?{id:entry.id}:{})}).map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&');wx.reLaunch({url:'/pages/'+entry.route+'/index'+(query?'?'+query:'')});},
 labQuery(e){const q=e.detail.value.toLowerCase();this.setData({filteredCatalog:this.data.catalog.filter(c=>[c.label,c.sourceQuery,c.route,String(c.index)].join(' ').toLowerCase().includes(q))});},
 reviewNext(e){const catalog=require('./mock/catalog'),index=this.data.reviewIndex+Number(e.currentTarget.dataset.delta);if(index<0||index>=catalog.length)return;this.closeSheet();this.setData({catalog});this.labOpen({currentTarget:{dataset:{index}}});},
  labPersona(e){api.mock.configure({persona:e.currentTarget.dataset.id});wx.reLaunch({url:'/pages/review-lab/index'});},
 labScenario(e){api.mock.configure({scenario:e.currentTarget.dataset.id});wx.reLaunch({url:'/pages/discover/index'});},
 labReset(){wx.showModal({title:'重置演示数据',content:'清空本地演示修改、草稿、身份与筛选，不影响 Montana 数据。',success:r=>{if(!r.confirm)return;const keys=wx.getStorageInfoSync().keys;keys.filter(k=>k.startsWith('706.draft.mock.')||k.startsWith('706.preferences.mock.')).forEach(k=>wx.removeStorageSync(k));api.mock.reset();wx.reLaunch({url:'/pages/review-lab/index'});}});},
 labMode(){const next=api.isMock()?'montana':'mock';wx.showModal({title:next==='montana'?'连接真实 Montana':'切换离线演示',content:next==='montana'?'真实模式使用独立账号和真实服务，操作可能保存到服务端。请先完成域名与账号配置。':'所有演示操作仅保存在本机。',success:r=>{if(!r.confirm)return;api.setMode(next);wx.reLaunch({url:'/pages/review-lab/index'});}});},
 savePoster(){return this.run(async()=>{await new Promise((resolve,reject)=>wx.saveImageToPhotosAlbum({filePath:this.data.posterPath,success:resolve,fail:reject}));wx.showToast({title:this.data.locale==='en'?'Poster saved':'海报已保存',icon:'success'});});}
};};
